export default [
  { value: "gmt-12:00", label: "(GMT -12:00) Eniwetok, Kwajalein" },
  { value: "gmt-11:00", label: "(GMT -11:00) Midway Island, Samoa" },
  { value: "gmt-10:00", label: "(GMT -10:00) Hawaii" },
  { value: "gmt-09:50", label: "(GMT -9:30) Taiohae" },
  { value: "gmt-09:00", label: "(GMT -9:00) Alaska" },
  { value: "gmt-08:00", label: "(GMT -8:00) Pacific Time (US & Canada)" },
  { value: "gmt-07:00", label: "(GMT -7:00) Mountain Time (US & Canada)" },
  { value: "gmt-06:00", label: "(GMT -6:00) Central Time (US & Canada), Mexico City" },
  { value: "gmt-05:00", label: "(GMT -5:00) Eastern Time (US & Canada), Bogota, Lima" },
  { value: "gmt-04:50", label: "(GMT -4:30) Caracas" },
  { value: "gmt-04:00", label: "(GMT -4:00) Atlantic Time (Canada), Caracas, La Paz" },
  { value: "gmt-03:50", label: "(GMT -3:30) Newfoundland" },
  { value: "gmt-03:00", label: "(GMT -3:00) Brazil, Buenos Aires, Georgetown" },
  { value: "gmt-02:00", label: "(GMT -2:00) Mid-Atlantic" },
  { value: "gmt-01:00", label: "(GMT -1:00) Azores, Cape Verde Islands" },
  { value: "gmt+00:00", label: "(GMT) Western Europe Time, London, Lisbon, Casablanca" },
  { value: "gmt+01:00", label: "(GMT +1:00) Brussels, Copenhagen, Madrid, Paris" },
  { value: "gmt+02:00", label: "(GMT +2:00) Kaliningrad, South Africa" },
  { value: "gmt+03:00", label: "(GMT +3:00) Baghdad, Riyadh, Moscow, St. Petersburg" },
  { value: "gmt+03:50", label: "(GMT +3:30) Tehran" },
  { value: "gmt+04:00", label: "(GMT +4:00) Abu Dhabi, Muscat, Baku, Tbilisi" },
  { value: "gmt+04:50", label: "(GMT +4:30) Kabul" },
  { value: "gmt+05:00", label: "(GMT +5:00) Ekaterinburg, Islamabad, Karachi, Tashkent" },
  { value: "gmt+05:50", label: "(GMT +5:30) Bombay, Calcutta, Madras, New Delhi" },
  { value: "gmt+05:75", label: "(GMT +5:45) Kathmandu, Pokhara" },
  { value: "gmt+06:00", label: "(GMT +6:00) Almaty, Dhaka, Colombo" },
  { value: "gmt+06:50", label: "(GMT +6:30) Yangon, Mandalay" },
  { value: "gmt+07:00", label: "(GMT +7:00) Bangkok, Hanoi, Jakarta" },
  { value: "gmt+08:00", label: "(GMT +8:00) Beijing, Perth, Singapore, Hong Kong" },
  { value: "gmt+08:75", label: "(GMT +8:45) Eucla" },
  { value: "gmt+09:00", label: "(GMT +9:00) Tokyo, Seoul, Osaka, Sapporo, Yakutsk" },
  { value: "gmt+09:50", label: "(GMT +9:30) Adelaide, Darwin" },
  { value: "gmt+10:00", label: "(GMT +10:00) Eastern Australia, Guam, Vladivostok" },
  { value: "gmt+10:50", label: "(GMT +10:30) Lord Howe Island" },
  { value: "gmt+11:00", label: "(GMT +11:00) Magadan, Solomon Islands, New Caledonia" },
  { value: "gmt+11:50", label: "(GMT +11:30) Norfolk Island" },
  { value: "gmt+12:00", label: "(GMT +12:00) Auckland, Wellington, Fiji, Kamchatka" },
  { value: "gmt+12:75", label: "(GMT +12:45) Chatham Islands" },
  { value: "gmt+13:00", label: "(GMT +13:00) Apia, Nukualofa" },
  { value: "gmt+14:00", label: "(GMT +14:00) Line Islands, Tokelau"}
];